### ISSUE TITLE
npm find broken, requests invalid URL, SyntaxError: Unexpected token I

### ISSUE THREAD

**Issue by deathcap** [deathcap/webnpm#7]
``` npm.commands.find()
bundle.js:76 npm command require /node_modules/npm/lib/search.js
undefined
bundle.js:174 npm
bundle.js:174  
bundle.js:174 WARN
bundle.js:174 
bundle.js:174  Building the local index for the first time, please be patient

cors.maxogden.com/-/all:1 GET http://cors.maxogden.com/-/all 404 (Invalid host)
bundle.js:174 npm
npm
bundle.js:174  
bundle.js:174 ERR!
bundle.js:174  
bundle.js:174 registry
bundle.js:174  error parsing json

bundle.js:77180 SyntaxError: Unexpected token I
Invalid host: -
    at Object.parse (native)
    at CachingRegistryClient.<anonymous> (http://localhost:9966/bundle.js:93458:23)
    at Request._callback (http://localhost:9966/bundle.js:93431:14)
    at Request.init.self.callback (http://localhost:9966/bundle.js:118022:22)
    at Request.EventEmitter.emit (http://localhost:9966/bundle.js:39086:17)
    at Request.<anonymous> (http://localhost:9966/bundle.js:118967:14)
    at Request.EventEmitter.emit (http://localhost:9966/bundle.js:39105:20)
    at null.<anonymous> (http://localhost:9966/bundle.js:118915:12)
    at EventEmitter.emit (http://localhost:9966/bundle.js:39105:20)
    at Response.handle (http://localhost:9966/bundle.js:39765:19)
```

something with the CORS proxy path (ref GH-1), since I'm setting:

``` javascript
var config = {
  registry: 'http://cors.maxogden.com/http://registry.npmjs.org'
};
```

**Comment by deathcap** [comment]
``` javascript
node_modules//npm/lib/cache/update-index.js:    full = url.resolve(uri, "/-/all")
```

> require('url').resolve('http://cors.maxogden.com/http://registry.npmjs.org', '/-/all')
> 'http://cors.maxogden.com/-/all'

**Comment by deathcap** [comment]
```
npm.commands.find('--verbose', 'foo')
bundle.js:97 npm command require /node_modules/npm/lib/search.js
undefined
bundle.js:205 npm
bundle.js:205  
bundle.js:205 WARN
bundle.js:205 
bundle.js:205  Building the local index for the first time, please be patient
```
